### Тестовые данные
GET http://localhost:5050/api HTTP/1.1

### Получить список фильмов
GET http://localhost:3000/films HTTP/1.1

### Получить список любимых фильмов
GET http://localhost:3000/films/favorite HTTP/1.1

### Изменить состояние фильма к просмотру
POST http://localhost:3000/films/favorite/6342c5045ad5c9057706c647/1 HTTP/1.1

### Получить фильм
GET http://localhost:3000/films/6342c5045ad5c9057706c64d HTTP/1.1

### Получить промо фильм
GET http://localhost:3000/films/promo HTTP/1.1

### Получить похожие фильмы
GET http://localhost:3000/films/6342c5045ad5c9057706c647/similar HTTP/1.1

### Удалить фильм
DELETE http://localhost:3000/films/634a685d3d4420e30ef908e7 HTTP/1.1

### Редактировать фильм
POST  http://localhost:3000/films/6342c5045ad5c9057706c64d HTTP/1.1
Content-Type: application/json

{
    "name": "What we do in the shadows",
    "posterImage": "https://10.react.pages.academy/static/film/poster/Snatch.jpg",
    "previewImage": "https://10.react.pages.academy/static/film/preview/snatch.jpg",
    "backgroundImage": "https://10.react.pages.academy/static/film/background/Snatch.jpg",
    "backgroundColor": "#FDFDFC",
    "description": "Unscrupulous boxing promoters, violent bookmakers.",
    "director": "Guy Ritchie",
    "starring": [
      "Jason Statham",
      "Benicio Del Toro"
    ],
    "runTime": 98,
    "genre": "Thriller",
    "released": 2009,
    "userId": "6342c5045ad5c9057706c644",
    "publishDate": "2022-09-28T13:48:56.371Z",
    "videoLink": "https://10.react.pages.academy/static/film/video/matrix.mp4",
    "previewVideoLink": "https://10.react.pages.academy/static/film/video/dog.mp4"
}

### Добавление новой карточки с фильмом
POST http://localhost:3000/films HTTP/1.1
Content-Type: application/json

{
    "name": "Snatch",
    "posterImage": "https://10.react.pages.academy/static/film/poster/Snatch.jpg",
    "previewImage": "https://10.react.pages.academy/static/film/preview/snatch.jpg",
    "backgroundImage": "https://10.react.pages.academy/static/film/background/Snatch.jpg",
    "backgroundColor": "#FDFDFC",
    "description": "Unscrupulous boxing promoters, violent bookmakers, a Russian gangster, incompetent amateur robbers and supposedly Jewish jewelers fight to track down a priceless stolen diamond.",
    "director": "Guy Ritchie",
    "starring": [
      "Jason Statham",
      "Brad Pitt",
      "Benicio Del Toro"
    ],
    "runTime": 104,
    "genre": "Comedy",
    "released": 2000,
    "userId": "6342c5045ad5c9057706c644",
    "publishDate": "2022-09-28T13:48:56.371Z",
    "videoLink": "https://10.react.pages.academy/static/film/video/matrix.mp4",
    "previewVideoLink": "https://10.react.pages.academy/static/film/video/dog.mp4"
}

### Регистрация пользователя
POST http://localhost:3000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "avatar": "torrance.png",
  "userName": "Jack Johnson",
  "password": "shining"
}

### Авторизация пользователя
POST http://localhost:3000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "shining"
}
